### ISSUE TITLE
Navigation Tools..

### ISSUE THREAD

**Issue by mayur9785** [friendde/ArcGIS_JS_NavigationTools#3]
Hii...

i tried adding related files css. js..etc...and modified viewer.js also but widget is not loading...
any idea how to add widgets ? what i am misssing..
i went to through the link tutorial but still widget not loading
https://github.com/friendde/ArcGIS_JS_NavigationTools/wiki/How-to-add-widget-to-CMV

**Comment by friendde** [comment]
Can you send the error message from the console? Which browser and what version are you using?

**Comment by mayur9785** [comment]
Thanks for your reply 

i solved by uncommenting the below lines in viewer.js file....and its worked for me now i can see widgets...thanks for navigation toolbar.

panes: {
top: {
        		id: 'sidebarTop',
        		placeAt: 'outer',
        		collapsible: true,
         		splitter: true,
         		region: 'top'
        	}
         },
